### ISSUE TITLE
Shouldn't the binprot `char` shape represent a single byte (and not a 4-byte type)?

### ISSUE THREAD

**Issue by base1172** [LaurentMazare/binprot-rs#6]
Should this be **`impl BinProtShape for u8`** instead of **`impl BinProtShape for char`**?  The Rust `char` primitive has a 4-byte representation, whereas the Ocaml `char` primitive is a single byte.

https://github.com/LaurentMazare/binprot-rs/blob/193d43059c8011279b8414d39f1665779432319d/src/shape.rs#L214-L218

**Comment by LaurentMazare** [comment]
Yeah this would probably be more relevant for u8 than for rust `char` type. That said `BinProtRead` and `BinProtWrite` are not implemented for `char` at the moment so it's not much of an issue.
